# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and FoD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Maven Version
      run: mvn -version
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Run FoD SAST Scan
      uses: fortify/github-action@v1
      with:
        sast-scan: true
      env:
        FOD_URL: https://ams.fortify.com
        FOD_TENANT: ${{secrets.FOD_TENANT}}
        FOD_USER: ${{secrets.FOD_USER}}
        FOD_PASSWORD: ${{secrets.FOD_PAT}}
        # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
        # FOD_RELEASE: MyApp:MyRelease
        FOD_RELEASE: your_email_address:IWA-Java-v1.0
        EXTRA_PACKAGE_OPTS: -oss
        DO_WAIT: true
        DO_EXPORT: true    
