name: Python 3 Django with FoD SAST SCA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
    
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install -r requirements.txt
        pipenv install -r requirements.txt
        
    #- name: Run Tests
    #  run: |
    #    python manage.py test
    - name: Run FoD SAST Scan
      uses: fortify/github-action@v1
      with:
        sast-scan: true
      env:
        FOD_URL: https://ams.fortify.com
        FOD_TENANT: ${{secrets.FOD_TENANT}}
        FOD_USER: ${{secrets.FOD_USER}}
        FOD_PASSWORD: ${{secrets.FOD_PAT}}
        # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
        # FOD_RELEASE: MyApp:MyRelease
        FOD_RELEASE: your_email_address:PythonGoat_v2.0.1
        EXTRA_PACKAGE_OPTS: -oss
        DO_WAIT: true
        DO_EXPORT: true
